### ISSUE TITLE
Sidebar has no theme

### ISSUE THREAD

**Issue by jjpb44** [mohvn/solarized-zenbrowser#1]
With recent Zen updates the sidebar loose the capability to get the theme.

**Comment by mohvn** [comment]
![image](https://github.com/user-attachments/assets/ff8c6204-a1f2-42f0-906a-8c86bdc0f5b2)
It's working fine here at 1.0.1-a.19 (Firefox 132.0.1) (64-bit)

Maybe you have some custom sidebar theme applied.

Remove all hex colors added here on custom sidebar color:
![image](https://github.com/user-attachments/assets/d7826c21-3165-44d6-afea-994c3f7d5b22)
